// SPDX-License-Identifier: GPL-3.0-only
/**
 * What mesh-todo says, in both languages: the labels, the LED, and the lines
 * the sync pane writes. The longer passages with markup are in the template,
 * one block per language. Protocol names — announce, want, blocks, beat,
 * echo — stay as the wire spells them.
 *
 * German without address, as on lora.le-space.de: no du, no Sie.
 */
const plural = (n, one, many) => (n === 1 ? one : many);

export const WORDS = {
  en: {
    title: "mesh-todo — a todo list over LoRa",
    tagline: (internet) =>
      `no servers · no accounts · ${internet ? "internet first, the mesh when it goes" : "no IP path"} — a todo list over LoRa`,
    linkKinds: { bc: "BroadcastChannel (fake mesh)", ble: "Meshtastic node (Web Bluetooth)" },
    led: {
      title:
        "Blinks until a LoRa node is connected and another device keeping this list answers its heartbeat. One round an hour: up to five beats a minute apart, until one is answered.",
      lost: "LoRa node lost — reload to reconnect",
      reconnecting: "LoRa node dropped — reconnecting…",
      connecting: "connecting to the LoRa node…",
      none: "no LoRa node connected",
      noList: "LoRa node connected — no list to listen for yet",
      starting: "LoRa node connected — starting the heartbeat…",
      cannot: (error) => `the heartbeat cannot go out: ${error}`,
      checking: (beat, of) => ` · checking again, beat ${beat} of ${of}`,
      answered: (others, ago) =>
        `${others === 1 ? "another device" : `${others} other devices`} with this list answered ${ago}`,
      alone: "no other device with this list answered",
      nextAt: (time) => ` — next heartbeat at ${time}`,
      looking: (beat, of) => `looking for another device with this list — beat ${beat} of ${of}`,
      justNow: "just now",
      minAgo: (n) => `${n} min ago`,
    },
    dismiss: "Got it — don't show again",
    internet: "0 · Internet",
    normalPath: "(the normal path)",
    online: "online",
    internetGone: "internet gone",
    relays: (connected, known) => `relays ${connected} of ${known} connected`,
    otherPages: (n) => `${n} other ${plural(n, "page", "pages")}`,
    connKinds: { relay: "relay", direct: "direct (WebRTC)", relayed: "through a relay", other: "other" },
    thisNode: "this node",
    connTimesTitle: "More than one connection of this kind to the same peer.",
    tallySent: (beats, echoes) => `sent ${beats} beat${beats === 1 ? "" : "s"}, ${echoes} echo${echoes === 1 ? "" : "es"}`,
    tallyReceived: (beats, echoes) =>
      `heard ${beats} beat${beats === 1 ? "" : "s"}, ${echoes} echo${echoes === 1 ? "" : "es"}`,
    tallyTitle:
      "Since this page opened. Sent stuck at zero means the node refuses to transmit; sent climbing with nothing heard means nobody answered.",
    node: "1 · Node",
    startingStack: "starting the local database stack…",
    connecting: "connecting…",
    region: "region",
    nodeAirtime: (percent) => `node airtime ${percent} %`,
    nodeAirtimeTitle:
      "the node's own measured TX utilisation — all of its traffic (beacons, telemetry, relaying), not just this app",
    channelTitle: "same channel name + key fingerprint on both phones = the nodes can decrypt each other",
    primaryChannel: "primary channel",
    key: "key",
    beatSwitch: "heartbeat on the air",
    beatSwitchTitle: "A few bytes an hour: is another device with this list within reach?",
    syncSwitch: "carry the list over the radio",
    syncSwitchTitle: "Off by default — the expensive half, and it only works once both devices are on the same channel.",
    logSwitch: "send the log to a watcher",
    logSwitchTitle: "Publishes each log line on a pubsub topic over the internet connection, for a third machine watching this run — not over the radio, so it costs no airtime and does nothing without internet. Live or nothing: a line nobody hears is gone. Off by default — a log carries channel names and node numbers.",
    txChannel: "TX channel:",
    txChannelTitle:
      "transmissions go on this channel — pick the same »name« ⌗fingerprint on both phones. Reception decodes every channel the node holds a key for.",
    primary: "primary",
    underAMinute: "in under a minute",
    inMinutes: (minutes) => `in about ${minutes} minutes`,
    perHour: (percent) => `${percent} % of an hour`,
    budgetTitle: "airtime budget left this hour",
    noDutyCycle: "no duty cycle in this region — pacing off, politeness on",
    connectNode: "Connect node",
    keepAwake: "keep the screen awake — Web Bluetooth pauses when the screen sleeps",
    linkDroppedNote: "link dropped — reconnecting automatically…",
    reload: "Reload & reconnect",
    list: "2 · List",
    newTodo: "new todo",
    placeholder: "Buy milk…",
    add: "Add",
    airtimeSpent: "Airtime spent",
    entries: (n) => `${n} ${plural(n, "entry", "entries")}`,
    viaInternet: "changes travel over the internet as you make them",
    untilSent: "changes stay here until you send them",
    untilNode: "changes stay here until a node carries them",
    linkLine: "The link to this list — or this page's QR code, top right — opens it on another device:",
    linkText: "link to this list",
    sending: "sending…",
    nothingToSend: "Nothing to send",
    sendChanges: (n) => `Send ${n} ${plural(n, "change", "changes")}`,
    askingAir: "asking the air…",
    appsOutThere: (n) => `${n} ${plural(n, "app", "apps")} out there`,
    keepingList: "keeping this list",
    lastWord: (seconds) => `, last word ${seconds} s ago`,
    nobodyAnswered: "nobody answered",
    radiosWithoutApp: "— radios can be in range without an app listening",
    nobodySpoken: "nobody has spoken here yet",
    whoTitle: "Two small messages, and the only way to tell an app from a radio",
    asking: "asking…",
    anyone: "Is anyone out there?",
    switching: "switching…",
    continueMesh: "Continue over the mesh",
    connectContinue: "Connect a node and continue over the mesh",
    stayInternet: "Stay on the internet",
    carriedBy: "carried by",
    theInternet: "the internet",
    theMesh: "the mesh",
    peersOverIp: (n) => `${n} ${plural(n, "peer", "peers")} over IP`,
    carryInternet: "Carry it over the internet instead",
    carryMesh: "Carry it over the mesh instead",
    connectCarry: "Connect a node and carry it over the mesh",
    inviteAgain: "Invite again",
    backUpTitle: "Backs up over the internet, then names it over the radio in one frame",
    needsInternet: "Needs internet",
    backingUp: "backing up…",
    backUpOffline: "Back up (needs internet)",
    backUp: "Back up & beam pointer",
    reset: "Reset (drops local copy)",
    joiningDelta: "joining — the first delta carries manifest, access controller and entries…",
    openingLink: "opening the list from its link — OrbitDB fetches it from the pages that have it…",
    pointerArrived: "a pointer arrived over the mesh — the list itself is on the internet:",
    backup: "backup",
    restoring: "Restoring…",
    restoreOffline: "Restore (needs internet)",
    restore: "Restore from the pointer",
    ignore: "Ignore",
    linkInvite: "a link names this list — without an internet path only the mesh can bring it here:",
    meshInvite: "invitation from the mesh:",
    joining: "Joining…",
    join: "Join this list",
    connectFirst: "connect a node first.",
    creatingOnAir: "Creating — first frames on the air…",
    creating: "Creating…",
    create: "Create a list",
    waitForInvite: "…or wait for an invitation to arrive over the mesh.",
    noNodeInternet:
      "No node needed: the internet carries the list, and its link — or this page's QR code — opens it on another device. A node connected later adds the mesh.",
    noNodeMesh: "No node needed to make it; one connected later carries it over the mesh.",
    syncPane: "3 · Sync pane",
    benchInstrument: "(the bench instrument)",
    frames: "frames",
    retransmitRounds: "retransmit rounds",
    estAirtime: "est. airtime",
    radioGaveUp: (n, last) => `radio gave up on ${n} ${plural(n, "frame", "frames")} (${last})`,
    quiet: "quiet.",
    neighbours: "4 · Mesh neighbours",
    heardByNode: (n) => `(${n} heard by this node)`,
    hide: "Hide",
    showNodes: (n) => `Show ${n} nodes`,
    ago: { s: (n) => `${n}s ago`, m: (n) => `${n}m ago`, h: (n) => `${n}h ago` },
    hops: (n) => ` · ${n} ${plural(n, "hop", "hops")}`,
    viaMqtt: " · via mqtt",
    designIssue: "design issue #1",
    source: "source",
    buildTitle: "version · commit · built (UTC)",
    errors: {
      gaveUp:
        "the radio link keeps dropping — this phone's Bluetooth is too unstable; reload to retry, or use desktop Chrome",
      joinNeedsNode: "joining over the mesh needs a node — connect one first",
    },
    log: {
      autoChannel: (index, name, fingerprint) => `TX channel → ${index} »${name}« ⌗${fingerprint} — chosen automatically`,
      beatOn: "heartbeat on — a few bytes an hour",
      beatOff: "heartbeat off — nothing of it goes on the air",
      syncOn: "list sync on — the radio carries changes again",
      syncOff: "list sync off — the radio carries the heartbeat and nothing else",
      logOn: "log going out on the field-log topic",
      logOff: "log stays on this device",
      handChannel: (index, name, fingerprint) => `TX channel → ${index} »${name}« ⌗${fingerprint}`,
      nodeChannel: (index, name, fingerprint, primary) =>
        `node reports channel ${index} »${name}« ⌗${fingerprint}${primary ? " · primary" : ""}`,
      wakeReleased: "screen wake lock released by the system",
      wakeOn: "screen wake lock on",
      wakeRefused: (message) => `! wake lock refused: ${message}`,
      wakeOff: "screen wake lock off",
      payloadRx: (bytes, id) => `⇠ payload ${bytes} B (msg ${id})`,
      delivered: (id, rounds) => `✓ delivered msg ${id} after ${rounds} round(s)`,
      giveup: (id, rounds, reason) => `✗ gave up on msg ${id} after ${rounds} round(s)${reason ? ` — ${reason}` : ""}`,
      synced: (n) => `⇅ joined ${n} ${plural(n, "entry", "entries")}`,
      syncError: (message) => `! sync: ${message}`,
      dbOpen: (address) => `db open: ${address}…`,
      attachedMesh: "the node carries the list now — invite sent",
      attachedQuiet: "the list has a mesh path now, quiet while the internet carries it — invite sent",
      attachFailed: (message) => `! attaching the node failed: ${message}`,
      heartbeatError: (message) => `! heartbeat: ${message}`,
      beat: (beat, of) => `♥ beat ${beat} of ${of} — is another device keeping this list?`,
      heard: (type, from) => `♥ ${type} from device ${from}`,
      echo: (to) => `♥ echo to device ${to}`,
      alone: (time) => `♥ nobody with this list answered — next heartbeat at ${time}`,
      windowError: (type, message) => `! window ${type}: ${message}`,
      gattProbeOn: "measuring Bluetooth operations — overlaps and failures only",
      gattQueueOn: "one Bluetooth operation at a time",
      internetUp: (source) => `internet path up — relays from ${source}`,
      relaysKnown: (n) => `${n} ${plural(n, "relay", "relays")} known`,
      internetBack: (n) => `internet back — ${n} ${plural(n, "peer", "peers")} over IP`,
      internetGone: "internet gone — no peer answers, and a dial to the relay failed too",
      region: (name) => `node reports region: ${name}`,
      nodeStatus: (name) => `node status: ${name}`,
      linkDropped: (n) => `link dropped — reconnecting (attempt ${n})…`,
      reconnected: "reconnected — resuming sync",
      gaveUp: "gave up reconnecting after repeated drops",
      pointerHeard: (address, cid) => `pointer for ${address}… → ${cid}…`,
      linkUp: (kind, region) => `link up: ${kind}, region ${region}`,
      creatingOnAir: "creating list — announce and invite go on the air…",
      creatingNoNode: "creating list — no node needed; one connected later gives it the mesh",
      inviteSent: "invite sent over the mesh",
      carriedInternetCreate: (courierQuiet) => `carried by the internet — OrbitDB's own sync${courierQuiet ? ", courier quiet" : ""}`,
      createFailed: (message) => `! create failed: ${message}`,
      joiningOnAir: "joining — bootstrap request goes on the air…",
      joinedInternet: "joined over the internet — OrbitDB is fetching the log",
      joiningDelta: "joining — waiting for the first delta…",
      joinFailed: (message) => `! join failed: ${message}`,
      openingLink: "opening the list from its link — OrbitDB fetches it from the pages that have it…",
      listOpen: (noNode) => `list open — the internet carries it${noNode ? ", no node needed" : ""}`,
      openFailed: (message) => `! opening the link failed: ${message}`,
      carriedInternet: "carried by the internet — the courier is quiet",
      carriedMesh: "carried by the mesh — OrbitDB's own sync is stopped",
      switchFailed: (message) => `! switch failed: ${message}`,
      askingAir: "asking the air: is another mesh-todo keeping this list?",
      appsAnswered: (n, ids) => `${n} ${plural(n, "app", "apps")} answered: ${ids}`,
      nobodyAnswered: "nobody answered — radios may be in range, but no app is keeping this list",
      askFailed: (message) => `! asking failed: ${message}`,
      backingUp: "backing up over the internet — the radio only carries the pointer…",
      pointerSent: (blocks, cid) => `pointer sent: ${blocks} blocks backed up, cid ${cid}…`,
      backupFailed: (message) => `! backup failed: ${message}`,
      restoring: "restoring from the pointer — fetching the backup over the internet…",
      restored: (entries, blocks) => `restored ${entries} entries from ${blocks} blocks — no radio`,
      restoreFailed: (message) => `! restore failed: ${message}`,
      announced: (n) => `→ announced${n ? ` — ${n} local change(s) offered` : ""}`,
      sendFailed: (message) => `! send failed: ${message}`,
    },
  },
  de: {
    title: "mesh-todo — eine Todo-Liste über LoRa",
    tagline: (internet) =>
      `keine Server · keine Konten · ${internet ? "zuerst das Internet, das Mesh, wenn es wegfällt" : "kein IP-Pfad"} — eine Todo-Liste über LoRa`,
    linkKinds: { bc: "BroadcastChannel (Mesh-Attrappe)", ble: "Meshtastic-Knoten (Web Bluetooth)" },
    led: {
      title:
        "Blinkt, bis ein LoRa-Knoten verbunden ist und ein anderes Gerät mit dieser Liste auf den Herzschlag antwortet. Eine Runde pro Stunde: bis zu fünf Schläge im Minutenabstand, bis einer beantwortet wird.",
      lost: "LoRa-Knoten verloren — neu laden, um neu zu verbinden",
      reconnecting: "LoRa-Knoten abgerissen — verbinde neu…",
      connecting: "verbinde mit dem LoRa-Knoten…",
      none: "kein LoRa-Knoten verbunden",
      noList: "LoRa-Knoten verbunden — noch keine Liste, auf die er horchen kann",
      starting: "LoRa-Knoten verbunden — der Herzschlag startet…",
      cannot: (error) => `der Herzschlag kann nicht hinaus: ${error}`,
      checking: (beat, of) => ` · prüfe erneut, Schlag ${beat} von ${of}`,
      answered: (others, ago) =>
        `${others === 1 ? "ein anderes Gerät" : `${others} andere Geräte`} mit dieser Liste ${others === 1 ? "hat" : "haben"} geantwortet, ${ago}`,
      alone: "kein anderes Gerät mit dieser Liste hat geantwortet",
      nextAt: (time) => ` — nächster Herzschlag um ${time}`,
      looking: (beat, of) => `suche ein anderes Gerät mit dieser Liste — Schlag ${beat} von ${of}`,
      justNow: "gerade eben",
      minAgo: (n) => `vor ${n} min`,
    },
    dismiss: "Verstanden — nicht mehr zeigen",
    internet: "0 · Internet",
    normalPath: "(der normale Weg)",
    online: "online",
    internetGone: "Internet weg",
    relays: (connected, known) => `Relays ${connected} von ${known} verbunden`,
    otherPages: (n) => `${n} ${plural(n, "andere Seite", "andere Seiten")}`,
    connKinds: { relay: "Relay", direct: "direkt (WebRTC)", relayed: "über ein Relay", other: "andere" },
    thisNode: "dieser Knoten",
    connTimesTitle: "Mehr als eine Verbindung dieser Art zu demselben Peer.",
    tallySent: (beats, echoes) =>
      `${beats} ${beats === 1 ? "Schlag" : "Schläge"} gesendet, ${echoes} ${echoes === 1 ? "Echo" : "Echos"}`,
    tallyReceived: (beats, echoes) =>
      `${beats} ${beats === 1 ? "Schlag" : "Schläge"} gehört, ${echoes} ${echoes === 1 ? "Echo" : "Echos"}`,
    tallyTitle:
      "Seit dem Öffnen dieser Seite. Bleibt »gesendet« bei null, sendet der Knoten nicht; steigt »gesendet«, ohne dass etwas gehört wird, antwortet niemand.",
    node: "1 · Knoten",
    startingStack: "der lokale Datenbank-Stack startet…",
    connecting: "verbinde…",
    region: "Region",
    nodeAirtime: (percent) => `Knoten-Sendezeit ${percent} %`,
    nodeAirtimeTitle:
      "die selbst gemessene Sendeauslastung des Knotens — sein gesamter Verkehr (Beacons, Telemetrie, Weiterleitung), nicht nur diese App",
    channelTitle:
      "gleicher Kanalname und Schlüssel-Fingerabdruck auf beiden Telefonen = die Knoten können einander entschlüsseln",
    primaryChannel: "Primärkanal",
    key: "Schlüssel",
    beatSwitch: "Herzschlag auf dem Funk",
    beatSwitchTitle: "Ein paar Bytes pro Stunde: ist ein anderes Gerät mit dieser Liste in Reichweite?",
    syncSwitch: "Liste über Funk tragen",
    syncSwitchTitle: "Standardmäßig aus — die teure Hälfte, und sie wirkt erst, wenn beide Geräte auf demselben Kanal sind.",
    logSwitch: "Log an einen Beobachter senden",
    logSwitchTitle: "Veröffentlicht jede Logzeile über die Internetverbindung auf einem Pubsub-Topic, für einen dritten Rechner, der diesen Lauf mitliest — nicht über den Funk, kostet also keine Sendezeit und tut ohne Internet nichts. Live oder gar nicht: Was niemand hört, ist weg. Standardmäßig aus — ein Log trägt Kanalnamen und Knotennummern.",
    txChannel: "Sendekanal:",
    txChannelTitle:
      "gesendet wird auf diesem Kanal — auf beiden Telefonen denselben »Namen« ⌗Fingerabdruck wählen. Empfangen wird auf jedem Kanal, für den der Knoten einen Schlüssel hat.",
    primary: "primär",
    underAMinute: "in weniger als einer Minute",
    inMinutes: (minutes) => `in etwa ${minutes} Minuten`,
    perHour: (percent) => `${percent} % pro Stunde`,
    budgetTitle: "verbleibendes Sendezeit-Budget dieser Stunde",
    noDutyCycle: "kein Duty Cycle in dieser Region — Pacing aus, Höflichkeit an",
    connectNode: "Knoten verbinden",
    keepAwake: "Bildschirm wach halten — Web Bluetooth pausiert, wenn der Bildschirm schläft",
    linkDroppedNote: "Verbindung abgerissen — verbinde automatisch neu…",
    reload: "Neu laden & verbinden",
    list: "2 · Liste",
    newTodo: "neues Todo",
    placeholder: "Milch kaufen…",
    add: "Hinzufügen",
    airtimeSpent: "Sendezeit aufgebraucht",
    entries: (n) => `${n} ${plural(n, "Eintrag", "Einträge")}`,
    viaInternet: "Änderungen reisen beim Schreiben über das Internet",
    untilSent: "Änderungen bleiben hier, bis sie gesendet werden",
    untilNode: "Änderungen bleiben hier, bis ein Knoten sie trägt",
    linkLine: "Der Link zu dieser Liste — oder der QR-Code dieser Seite, oben rechts — öffnet sie auf einem anderen Gerät:",
    linkText: "Link zu dieser Liste",
    sending: "sende…",
    nothingToSend: "Nichts zu senden",
    sendChanges: (n) => `${n} ${plural(n, "Änderung", "Änderungen")} senden`,
    askingAir: "frage die Luft…",
    appsOutThere: (n) => `${n} ${plural(n, "App", "Apps")} da draußen`,
    keepingList: "mit dieser Liste",
    lastWord: (seconds) => `, zuletzt vor ${seconds} s`,
    nobodyAnswered: "niemand hat geantwortet",
    radiosWithoutApp: "— Funkgeräte können in Reichweite sein, ohne dass eine App zuhört",
    nobodySpoken: "hier hat noch niemand gesprochen",
    whoTitle: "Zwei kleine Nachrichten — und der einzige Weg, eine App von einem Funkgerät zu unterscheiden",
    asking: "frage…",
    anyone: "Ist da jemand?",
    switching: "wechsle…",
    continueMesh: "Über das Mesh weitermachen",
    connectContinue: "Knoten verbinden und über das Mesh weitermachen",
    stayInternet: "Beim Internet bleiben",
    carriedBy: "getragen von",
    theInternet: "dem Internet",
    theMesh: "dem Mesh",
    peersOverIp: (n) => `${n} ${plural(n, "Peer", "Peers")} über IP`,
    carryInternet: "Stattdessen über das Internet tragen",
    carryMesh: "Stattdessen über das Mesh tragen",
    connectCarry: "Knoten verbinden und über das Mesh tragen",
    inviteAgain: "Erneut einladen",
    backUpTitle: "Sichert über das Internet und nennt die Sicherung dann per Funk in einem Frame",
    needsInternet: "Braucht Internet",
    backingUp: "sichere…",
    backUpOffline: "Sichern (braucht Internet)",
    backUp: "Sichern & Zeiger funken",
    reset: "Zurücksetzen (verwirft die lokale Kopie)",
    joiningDelta: "Beitritt läuft — das erste Delta bringt Manifest, Access Controller und Einträge…",
    openingLink: "die Liste wird über ihren Link geöffnet — OrbitDB holt sie von den Seiten, die sie haben…",
    pointerArrived: "ein Zeiger kam über das Mesh — die Liste selbst liegt im Internet:",
    backup: "Sicherung",
    restoring: "Stelle wieder her…",
    restoreOffline: "Wiederherstellen (braucht Internet)",
    restore: "Aus dem Zeiger wiederherstellen",
    ignore: "Ignorieren",
    linkInvite: "ein Link nennt diese Liste — ohne Internetpfad kann nur das Mesh sie herbringen:",
    meshInvite: "Einladung aus dem Mesh:",
    joining: "Trete bei…",
    join: "Dieser Liste beitreten",
    connectFirst: "zuerst einen Knoten verbinden.",
    creatingOnAir: "Lege an — erste Frames auf der Luft…",
    creating: "Lege an…",
    create: "Liste anlegen",
    waitForInvite: "…oder auf eine Einladung aus dem Mesh warten.",
    noNodeInternet:
      "Kein Knoten nötig: Das Internet trägt die Liste, und ihr Link — oder der QR-Code dieser Seite — öffnet sie auf einem anderen Gerät. Ein später verbundener Knoten fügt das Mesh hinzu.",
    noNodeMesh: "Zum Anlegen ist kein Knoten nötig; ein später verbundener trägt die Liste über das Mesh.",
    syncPane: "3 · Sync-Bereich",
    benchInstrument: "(das Messinstrument)",
    frames: "Frames",
    retransmitRounds: "Wiederholungsrunden",
    estAirtime: "geschätzte Sendezeit",
    radioGaveUp: (n, last) => `Funk gab bei ${n} ${plural(n, "Frame", "Frames")} auf (${last})`,
    quiet: "still.",
    neighbours: "4 · Mesh-Nachbarn",
    heardByNode: (n) => `(${n} von diesem Knoten gehört)`,
    hide: "Ausblenden",
    showNodes: (n) => `${n} Knoten zeigen`,
    ago: { s: (n) => `vor ${n} s`, m: (n) => `vor ${n} min`, h: (n) => `vor ${n} h` },
    hops: (n) => ` · ${n} ${plural(n, "Hop", "Hops")}`,
    viaMqtt: " · über MQTT",
    designIssue: "Entwurfs-Issue #1",
    source: "Quellcode",
    buildTitle: "Version · Commit · gebaut (UTC)",
    errors: {
      gaveUp:
        "die Funkverbindung reißt immer wieder ab — das Bluetooth dieses Telefons ist zu instabil; neu laden oder Chrome auf dem Desktop verwenden",
      joinNeedsNode: "Beitreten über das Mesh braucht einen Knoten — zuerst einen verbinden",
    },
    log: {
      autoChannel: (index, name, fingerprint) => `Sendekanal → ${index} »${name}« ⌗${fingerprint} — automatisch gewählt`,
      beatOn: "Herzschlag an — ein paar Bytes pro Stunde",
      beatOff: "Herzschlag aus — davon geht nichts auf den Funk",
      syncOn: "Listen-Sync an — der Funk trägt wieder Änderungen",
      syncOff: "Listen-Sync aus — der Funk trägt den Herzschlag und sonst nichts",
      logOn: "Log geht auf das Feldlog-Topic hinaus",
      logOff: "Log bleibt auf diesem Gerät",
      handChannel: (index, name, fingerprint) => `Sendekanal → ${index} »${name}« ⌗${fingerprint}`,
      nodeChannel: (index, name, fingerprint, primary) =>
        `Knoten meldet Kanal ${index} »${name}« ⌗${fingerprint}${primary ? " · primär" : ""}`,
      wakeReleased: "Bildschirmsperre vom System freigegeben",
      wakeOn: "Bildschirm bleibt wach",
      wakeRefused: (message) => `! Wachhalten abgelehnt: ${message}`,
      wakeOff: "Bildschirm darf wieder schlafen",
      payloadRx: (bytes, id) => `⇠ Payload ${bytes} B (Nachricht ${id})`,
      delivered: (id, rounds) => `✓ Nachricht ${id} zugestellt nach ${rounds} Runde(n)`,
      giveup: (id, rounds, reason) => `✗ Nachricht ${id} aufgegeben nach ${rounds} Runde(n)${reason ? ` — ${reason}` : ""}`,
      synced: (n) => `⇅ ${n} ${plural(n, "Eintrag", "Einträge")} übernommen`,
      syncError: (message) => `! Sync: ${message}`,
      dbOpen: (address) => `DB offen: ${address}…`,
      attachedMesh: "der Knoten trägt die Liste jetzt — Einladung gesendet",
      attachedQuiet: "die Liste hat jetzt einen Mesh-Pfad, still, solange das Internet sie trägt — Einladung gesendet",
      attachFailed: (message) => `! Anbinden des Knotens fehlgeschlagen: ${message}`,
      heartbeatError: (message) => `! Herzschlag: ${message}`,
      beat: (beat, of) => `♥ Schlag ${beat} von ${of} — führt ein anderes Gerät diese Liste?`,
      heard: (type, from) => `♥ ${type} von Gerät ${from}`,
      echo: (to) => `♥ Echo an Gerät ${to}`,
      alone: (time) => `♥ niemand mit dieser Liste hat geantwortet — nächster Herzschlag um ${time}`,
      windowError: (type, message) => `! Fenster ${type}: ${message}`,
      gattProbeOn: "messe Bluetooth-Operationen — nur Überlappungen und Fehler",
      gattQueueOn: "immer nur eine Bluetooth-Operation gleichzeitig",
      internetUp: (source) => `Internetpfad steht — Relays aus ${source}`,
      relaysKnown: (n) => `${n} ${plural(n, "Relay", "Relays")} bekannt`,
      internetBack: (n) => `Internet wieder da — ${n} ${plural(n, "Peer", "Peers")} über IP`,
      internetGone: "Internet weg — kein Peer antwortet, und ein Verbindungsversuch zum Relay schlug ebenfalls fehl",
      region: (name) => `Knoten meldet Region: ${name}`,
      nodeStatus: (name) => `Knotenstatus: ${name}`,
      linkDropped: (n) => `Verbindung abgerissen — neuer Versuch (${n})…`,
      reconnected: "wieder verbunden — der Sync geht weiter",
      gaveUp: "Neuverbinden nach wiederholten Abbrüchen aufgegeben",
      pointerHeard: (address, cid) => `Zeiger für ${address}… → ${cid}…`,
      linkUp: (kind, region) => `Verbindung steht: ${kind}, Region ${region}`,
      creatingOnAir: "Liste wird angelegt — Ankündigung und Einladung gehen auf die Luft…",
      creatingNoNode: "Liste wird angelegt — kein Knoten nötig; ein später verbundener gibt ihr das Mesh",
      inviteSent: "Einladung über das Mesh gesendet",
      carriedInternetCreate: (courierQuiet) => `vom Internet getragen — OrbitDBs eigener Sync${courierQuiet ? ", Kurier still" : ""}`,
      createFailed: (message) => `! Anlegen fehlgeschlagen: ${message}`,
      joiningOnAir: "Beitritt — die Bootstrap-Anfrage geht auf die Luft…",
      joinedInternet: "über das Internet beigetreten — OrbitDB holt das Log",
      joiningDelta: "Beitritt — warte auf das erste Delta…",
      joinFailed: (message) => `! Beitritt fehlgeschlagen: ${message}`,
      openingLink: "die Liste wird über ihren Link geöffnet — OrbitDB holt sie von den Seiten, die sie haben…",
      listOpen: (noNode) => `Liste offen — das Internet trägt sie${noNode ? ", kein Knoten nötig" : ""}`,
      openFailed: (message) => `! Öffnen des Links fehlgeschlagen: ${message}`,
      carriedInternet: "vom Internet getragen — der Kurier ist still",
      carriedMesh: "vom Mesh getragen — OrbitDBs eigener Sync ist gestoppt",
      switchFailed: (message) => `! Wechsel fehlgeschlagen: ${message}`,
      askingAir: "frage die Luft: führt eine andere mesh-todo diese Liste?",
      appsAnswered: (n, ids) => `${n} ${plural(n, "App hat", "Apps haben")} geantwortet: ${ids}`,
      nobodyAnswered: "niemand hat geantwortet — Funkgeräte mögen in Reichweite sein, aber keine App führt diese Liste",
      askFailed: (message) => `! Fragen fehlgeschlagen: ${message}`,
      backingUp: "Sicherung über das Internet — der Funk trägt nur den Zeiger…",
      pointerSent: (blocks, cid) => `Zeiger gesendet: ${blocks} Blöcke gesichert, CID ${cid}…`,
      backupFailed: (message) => `! Sicherung fehlgeschlagen: ${message}`,
      restoring: "Wiederherstellung aus dem Zeiger — die Sicherung kommt über das Internet…",
      restored: (entries, blocks) => `${entries} Einträge aus ${blocks} Blöcken wiederhergestellt — ohne Funk`,
      restoreFailed: (message) => `! Wiederherstellung fehlgeschlagen: ${message}`,
      announced: (n) => `→ angekündigt${n ? ` — ${n} lokale Änderung(en) angeboten` : ""}`,
      sendFailed: (message) => `! Senden fehlgeschlagen: ${message}`,
    },
  },
};
