// SPDX-License-Identifier: GPL-3.0-only
/**
 * What Termine über Funk says, in both languages. The German is the page's
 * original voice and speaks to its reader as du, as a booking page for a
 * shop's customers does; the English is its counterpart. The longer passages
 * with markup are in the template, one block per language.
 *
 * The shop's own data — its name, its services — is the salon's, and stays as
 * the salon wrote it.
 */
const WEEKDAYS = {
  de: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
  en: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
const MONTHS_EN = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const pad = (n) => String(n).padStart(2, "0");

export const WORDS = {
  de: {
    title: "Termine über Funk",
    weekdays: WEEKDAYS.de,
    /** A booking's moment, as a German calendar writes it. */
    when: (weekday, w) => `${weekday}, ${w.day}.${w.month}. ${pad(w.hour)}:${pad(w.minute)} Uhr`,
    eyebrow: "funkpost · Termine",
    tag: "Terminbuchung über ein LoRa-Mesh — ohne Server, ohne Internet",
    dismiss: "Verstanden — nicht mehr zeigen",
    linkKinds: { bc: "BroadcastChannel (Mesh-Attrappe)", ble: "Meshtastic®-Knoten (Web Bluetooth)" },
    link: {
      off: "kein Funk",
      waiting: "Funk offen, noch niemand gehört",
      lastHeard: (minutes) => `zuletzt gehört vor ${minutes} min`,
      answers: "Mesh antwortet",
      inRange: (n) => `${n} ${n === 1 ? "Gerät" : "Geräte"} in Reichweite`,
    },
    perHour: (percent) => `${percent} % pro Stunde`,
    underAMinute: "in weniger als einer Minute",
    inMinutes: (minutes) => `in etwa ${minutes} Minuten`,
    txChannel: "Sendekanal:",
    txChannelTitle:
      "Gesendet wird auf diesem Kanal — auf beiden Geräten derselbe »Name« ⌗Fingerabdruck. Empfangen wird auf allen, für die der Knoten einen Schlüssel hat.",
    primary: "primär",
    defaultChannel: "(Standard)",
    thisNode: "dieser Knoten",
    keepAwake: "Bildschirm anlassen — Bluetooth pausiert, wenn das Display schläft",
    whoAreYou: "Wer bist du?",
    iAmSalon: "Ich bin der Salon",
    iWantAppointment: "Ich möchte einen Termin",
    rolesHint: "Der Salon führt das Buch und entscheidet. Beide Seiten sprechen nur über Funk.",
    radio: "Funk",
    connecting: "verbinde…",
    connect: "Knoten verbinden",
    loading: "Termine werden geladen…",
    bookWith: "Termin buchen bei",
    service: "Leistung",
    firstName: "Dein Vorname",
    autoConfirms: "Freie Zeiten werden sofort bestätigt.",
    salonConfirms: "Der Salon bestätigt jede Anfrage einzeln.",
    closed: "An diesem Tag ist zu.",
    airtimeSpent: "Sendezeit aufgebraucht",
    book: "Termin buchen",
    request: "Termin anfragen",
    searching: "Termin wird gesucht",
    searchingHint:
      "Der Link hat den Termin mitgebracht — er wird jetzt über Funk geholt. Diese Seite kam von einem Webserver; alles Weitere läuft über das Mesh.",
    yourAppointments: "Deine Termine",
    ics: "Termin.ics",
    cancel: "Absagen",
    dayPlan: "Tagesplan",
    autoConfirm: "Autobestätigung",
    askFirst: "Rückfrage",
    newRequest: "Neue Anfrage über Funk",
    wouldLike: "möchte",
    confirm: "Bestätigen",
    decline: "Ablehnen",
    free: "frei",
    status: {
      confirmed: "bestätigt",
      pending: "wartet auf den Salon",
      declined: "abgelehnt",
      cancelled: "abgesagt",
      superseded: "Zeit war vergeben",
    },
    radioStrip: "Funkstreifen",
    rounds: "Runden",
    givenUp: "Aufgegeben",
    givenUpTitle: (last) => `Frames, für die das Funkgerät seine Wiederholungen aufgebraucht hat — ${last}`,
    payloads: "Sendungen",
    quiet: "still.",
    source: "Quelltext",
    design: "Entwurf #38",
    gaveUp: "Der Funkkontakt bricht immer wieder ab — bitte neu laden.",
    salonTaken:
      "Dieser Salon wird bereits von einem anderen Gerät geführt. Bestätigen kann nur dieses eine Gerät — hier lässt sich der Tagesplan ansehen.",
    log: {
      autoChannel: (index, name, fingerprint) => `Sendekanal → ${index} »${name}« ⌗${fingerprint} — automatisch gewählt`,
      handChannel: (index, name, fingerprint) => `Sendekanal → ${index} »${name}« ⌗${fingerprint} — grüße neu`,
      channel: (index, name, fingerprint, primary) =>
        `Kanal ${index} »${name}« ⌗${fingerprint}${primary ? " · primär" : ""}`,
      wakeReleased: "Bildschirmsperre vom System wieder freigegeben",
      wakeOn: "Bildschirm bleibt an",
      wakeRefused: (message) => `! Bildschirmsperre abgelehnt: ${message}`,
      wakeOff: "Bildschirm darf wieder schlafen",
      storage: (message) => `! Speicher: ${message}`,
      restored: (n) => `${n} Einträge aus dem Gerät geladen`,
      airtimeSpent: "Sendezeit für diese Stunde aufgebraucht — wartet, bis wieder Budget da ist",
      gaveUp: (id, rounds) => `✗ ${id} nach ${rounds} Runden aufgegeben`,
      accepted: (id) => `⇠ Eintrag übernommen (${id})`,
      rejected: "⊘ Eintrag verworfen — Signatur passt nicht",
      digest: (bytes) => `→ Digest ${bytes} B`,
      booking: (bytes) => `→ Buchung ${bytes} B`,
      regionUnset: "Knoten meldet seine Region noch nicht — warte damit (Funkrecht)",
      region: (name) => `Knoten meldet Region ${name}`,
      nodeStatus: (name) => `Knoten: ${name}`,
      reconnecting: (n) => `Verbindung weg — Versuch ${n}…`,
      reattached: "Schreibkanal war kurz gestört — repariert, Verbindung stand durchgehend",
      reconnected: "wieder verbunden",
      salonPublished: "Salon-Identität veröffentlicht",
      radioOpen: (kind) => `Funk offen: ${kind}`,
      requested: "Anfrage ist auf der Luft",
      confirmed: "bestätigt — Antwort geht raus",
      declined: "abgelehnt — Antwort geht raus",
      cancelled: "Absage ist auf der Luft",
      saved: (filename) => `${filename} gespeichert`,
    },
  },
  en: {
    title: "Termine über Funk — appointments over the radio",
    weekdays: WEEKDAYS.en,
    when: (weekday, w) => `${weekday} ${w.day} ${MONTHS_EN[w.month - 1]}, ${pad(w.hour)}:${pad(w.minute)}`,
    eyebrow: "funkpost · appointments",
    tag: "Appointments booked over a LoRa mesh — no server, no internet",
    dismiss: "Got it — don't show again",
    linkKinds: { bc: "BroadcastChannel (fake mesh)", ble: "Meshtastic® node (Web Bluetooth)" },
    link: {
      off: "no radio",
      waiting: "radio open, nobody heard yet",
      lastHeard: (minutes) => `last heard ${minutes} min ago`,
      answers: "the mesh answers",
      inRange: (n) => `${n} ${n === 1 ? "device" : "devices"} in range`,
    },
    perHour: (percent) => `${percent} % of an hour`,
    underAMinute: "in under a minute",
    inMinutes: (minutes) => `in about ${minutes} minutes`,
    txChannel: "TX channel:",
    txChannelTitle:
      "Transmissions go on this channel — the same »name« ⌗fingerprint on both devices. Reception covers every channel the node holds a key for.",
    primary: "primary",
    defaultChannel: "(default)",
    thisNode: "this node",
    keepAwake: "keep the screen on — Bluetooth pauses when the display sleeps",
    whoAreYou: "Who are you?",
    iAmSalon: "I am the salon",
    iWantAppointment: "I would like an appointment",
    rolesHint: "The salon keeps the book and decides. Both sides talk over the radio only.",
    radio: "Radio",
    connecting: "connecting…",
    connect: "Connect node",
    loading: "Loading appointments…",
    bookWith: "Book an appointment with",
    service: "Service",
    firstName: "Your first name",
    autoConfirms: "Free times are confirmed at once.",
    salonConfirms: "The salon confirms each request itself.",
    closed: "Closed on this day.",
    airtimeSpent: "Airtime spent",
    book: "Book the appointment",
    request: "Request the appointment",
    searching: "Looking for the appointment",
    searchingHint:
      "The link brought the appointment with it — it is being fetched over the radio now. This page came from a web server; everything else runs over the mesh.",
    yourAppointments: "Your appointments",
    ics: "Appointment.ics",
    cancel: "Cancel",
    dayPlan: "Day plan",
    autoConfirm: "Auto-confirm",
    askFirst: "Ask first",
    newRequest: "New request over the radio",
    wouldLike: "would like",
    confirm: "Confirm",
    decline: "Decline",
    free: "free",
    status: {
      confirmed: "confirmed",
      pending: "waiting for the salon",
      declined: "declined",
      cancelled: "cancelled",
      superseded: "slot was taken",
    },
    radioStrip: "Radio strip",
    rounds: "rounds",
    givenUp: "given up",
    givenUpTitle: (last) => `Frames the radio used up its retries on — ${last}`,
    payloads: "payloads",
    quiet: "quiet.",
    source: "source",
    design: "design #38",
    gaveUp: "The radio link keeps dropping — reload the page to try again.",
    salonTaken:
      "Another device already keeps this salon's book. Only that device can confirm — this one can show the day plan.",
    log: {
      autoChannel: (index, name, fingerprint) => `TX channel → ${index} »${name}« ⌗${fingerprint} — chosen automatically`,
      handChannel: (index, name, fingerprint) => `TX channel → ${index} »${name}« ⌗${fingerprint} — greeting again`,
      channel: (index, name, fingerprint, primary) =>
        `channel ${index} »${name}« ⌗${fingerprint}${primary ? " · primary" : ""}`,
      wakeReleased: "screen wake lock released by the system",
      wakeOn: "screen stays on",
      wakeRefused: (message) => `! wake lock refused: ${message}`,
      wakeOff: "screen may sleep again",
      storage: (message) => `! storage: ${message}`,
      restored: (n) => `${n} entries loaded from this device`,
      airtimeSpent: "airtime for this hour spent — waiting until there is budget again",
      gaveUp: (id, rounds) => `✗ ${id} given up after ${rounds} rounds`,
      accepted: (id) => `⇠ entry accepted (${id})`,
      rejected: "⊘ entry rejected — the signature does not match",
      digest: (bytes) => `→ digest ${bytes} B`,
      booking: (bytes) => `→ booking ${bytes} B`,
      regionUnset: "the node has not reported its region yet — waiting (radio law)",
      region: (name) => `node reports region ${name}`,
      nodeStatus: (name) => `node: ${name}`,
      reconnecting: (n) => `link lost — attempt ${n}…`,
      reattached: "the write channel faltered briefly — repaired, the link held throughout",
      reconnected: "reconnected",
      salonPublished: "salon identity published",
      radioOpen: (kind) => `radio open: ${kind}`,
      requested: "the request is on the air",
      confirmed: "confirmed — the answer goes out",
      declined: "declined — the answer goes out",
      cancelled: "the cancellation is on the air",
      saved: (filename) => `${filename} saved`,
    },
  },
};
